version: '3'


services:

  db:
    container_name: ALAMIN_ROCKS_DB
    image: postgres:9.6
    networks:
      - arnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "30001:5432"

  backend:
    container_name: ALAMIN_ROCKS_BACKEND
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "cd /app/src && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - arnet
    ports:
      - "30002:8000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=4zkkt@3uh1!go@@ye3dm^zsvkx)-qn5-(u=xx3!--uluerupt=
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - PG_HOST=ALAMIN_ROCKS_DB
      - PG_PORT=5432
      - PG_DB_NAME=postgres
      - PG_DB_USER=postgres
      - PG_DB_PASSWORD=
      - ALAMIN_ROCKS_FRONTEND_URL=http://localhost:30003

  frontend:
    container_name: ALAMIN_ROCKS_FRONTEND
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/app:/app
    ports:
      - "30003:8080"
    networks:
      - arnet


networks:
  arnet:


volumes:
  pgdata: